[model]
MODEL_NAME = "sentence-transformers/paraphrase-MiniLM-L6-v2"

[text_splitter]
CHUNK_SIZE = 250
CHUNK_OVERLAP = 20

[pinecone]
index="ray-chatbot"
top_k=2
pdf_namespace="pdf"
text_namespace="text"
link_namespace="link"
qNa_namespace="qNa"